name: Dependency Check

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  workflow_dispatch:

jobs:
  dependency-check:
    name: Check Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties
      
    - name: Run dependency updates check
      run: ./gradlew dependencyUpdates --stacktrace
      
    - name: Upload dependency report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-updates-report
        path: build/dependencyUpdates/report.json
        
    - name: Create issue with dependency updates
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = 'build/dependencyUpdates/report.json';
          
          if (fs.existsSync(path)) {
            const report = fs.readFileSync(path, 'utf8');
            const reportData = JSON.parse(report);
            
            // Check if there are updates available
            const hasUpdates = reportData.outdated && reportData.outdated.dependencies && reportData.outdated.dependencies.length > 0;
            
            if (hasUpdates) {
              const dependencies = reportData.outdated.dependencies.map(dep => 
                `- **${dep.group}:${dep.name}**: ${dep.version} → ${dep.available.milestone || dep.available.release}`
              ).join('\n');
              
              const issueBody = `## 📦 Dependency Updates Available
              
              Automated dependency check has found available updates:
              
              ### Outdated Dependencies:
              ${dependencies}
              
              ### Full Report:
              \`\`\`json
              ${JSON.stringify(reportData, null, 2)}
              \`\`\`
              
              Please review and update dependencies as needed.
              
              _This issue was created automatically by the dependency check workflow._`;
              
              // Create or update issue
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `📦 Weekly Dependency Updates - ${new Date().toISOString().split('T')[0]}`,
                body: issueBody,
                labels: ['dependencies', 'automated']
              });
            }
          }
